services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - 8080:8080
    env_file:
      - ./user-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - elasticsearch
    networks:
      - user-network

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - user-network
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - user-network

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-network
  
  elasticsearch:
    image: elasticsearch:9.0.4
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    networks:
      - user-network
  
volumes:
  postgres_data:

networks:
  user-network:
    driver: bridge